server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server #服务名称
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false #不从eureka 上来捕获服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/